/**
 * Poketopia - Party Finder Data
 * Contém as definições de funções, pokémons disponíveis e dados iniciais.
 */

const availableRoles = [
    { id: 'tank', name: 'Tanker', icon: 'assets/icons/pve_tanker.png' },
    { id: 'otanker', name: 'Offensive Tanker', icon: 'assets/icons/pve_offensive_tanker.png' },
    { id: 'otdd', name: 'Over Time DD', icon: 'assets/icons/pve_over_time_damage_dealer.png' },
    { id: 'bdd', name: 'Burst DD', icon: 'assets/icons/pve_burst_damage_dealer.png' },
    { id: 'sot', name: 'Support OT', icon: 'assets/icons/pve_support_over_time.png' }
];

const availablePokemons = [
    { dex: 9, name: 'Blastoise', roles: ["tank"], isShiny: false },
    { dex: 9, name: 'Shiny Blastoise', roles: ["tank"], isShiny: true },
    { dex: 248, name: 'Tyranitar', roles: ["otdd"], isShiny: false },
    { dex: 149, name: 'Dragonite', roles: ["otdd"], isShiny: false },
    { dex: 131, name: 'Lapras', roles: ["bdd"], isShiny: false },
    { dex: 208, name: 'Steelix', roles: ["otdd"], isShiny: false },
    { dex: 464, name: 'Rhyperior', roles: ["bdd"], isShiny: false },
    { dex: 473, name: 'Mamoswine', roles: ["otdd"], isShiny: false },
    { dex: 445, name: 'Garchomp', roles: ["bdd"], isShiny: false },
    { dex: 395, name: 'Empoleon', roles: ["otdd"], isShiny: false },
    { dex: 59, name: 'Arcanine', roles: ["otdd"], isShiny: false },
    { dex: 359, name: 'Absol', roles: ["otdd"], isShiny: false },
    { dex: 617, name: 'Accelgor', roles: ["otdd"], isShiny: false },
    { dex: 142, name: 'Aerodactyl', roles: ["otdd"], isShiny: false },
    { dex: 65, name: 'Alakazam', roles: ["bdd"], isShiny: false },
    { dex: 869, name: 'Alcremie', roles: ["bdd"], isShiny: false },
    { dex: 51, name: 'Alolan Dugtrio', roles: ["bdd"], isShiny: false },
    { dex: 76, name: 'Alolan Golem', roles: ["otdd"], isShiny: false },
    { dex: 89, name: 'Alolan Muk', roles: ["bdd"], isShiny: false },
    { dex: 53, name: 'Alolan Persian', roles: ["tank"], isShiny: false },
    { dex: 594, name: 'Alomomola', roles: ["sot"], isShiny: false },
    { dex: 424, name: 'Ambipom', roles: ["otdd"], isShiny: false },
    { dex: 181, name: 'Ampharos', roles: ["tank"], isShiny: false },
    { dex: 683, name: 'Aromatisse', roles: ["sot"], isShiny: false },
    { dex: 713, name: 'Avalugg', roles: ["tank"], isShiny: false },
    { dex: 184, name: 'Azumarill', roles: ["bdd"], isShiny: false },
    { dex: 354, name: 'Banette', roles: ["bdd"], isShiny: false },
    { dex: 689, name: 'Barbaracle', roles: ["bdd"], isShiny: false },
    { dex: 614, name: 'Beartic', roles: ["otdd"], isShiny: false },
    { dex: 95, name: 'Big Onix', roles: ["tank"], isShiny: false },
    { dex: 628, name: 'Braviary', roles: ["bdd"], isShiny: false },
    { dex: 437, name: 'Bronzong', roles: ["bdd"], isShiny: false },
    { dex: 36, name: 'Clefable', roles: ["tank"], isShiny: false },
    { dex: 563, name: 'Cofagrigus', roles: ["otdd"], isShiny: false },
    { dex: 534, name: 'Conkeldurr', roles: ["otdd"], isShiny: false },
    { dex: 879, name: 'Copperajah', roles: ["otdd"], isShiny: false },
    { dex: 169, name: 'Crobat', roles: ["bdd"], isShiny: false },
    { dex: 95, name: 'Crystal Onix', roles: ["bdd"], isShiny: false },
    { dex: 148, name: 'Dragonair', roles: ["bdd"], isShiny: false },
    { dex: 621, name: 'Druddigon', roles: ["bdd"], isShiny: false },
    { dex: 356, name: 'Dusclops', roles: ["tank"], isShiny: false },
    { dex: 477, name: 'Dusknoir', roles: ["bdd"], isShiny: false },
    { dex: 125, name: 'Electabuzz', roles: ["otdd"], isShiny: false },
    { dex: 466, name: 'Electivire', roles: ["bdd"], isShiny: false },
    { dex: 196, name: 'Espeon', roles: ["bdd"], isShiny: false },
    { dex: 295, name: 'Exploud', roles: ["bdd"], isShiny: false },
    { dex: 160, name: 'Feraligatr', roles: ["bdd"], isShiny: false },
    { dex: 136, name: 'Flareon', roles: ["bdd"], isShiny: false },
    { dex: 671, name: 'Florges', roles: ["otdd"], isShiny: false },
    { dex: 478, name: 'Froslass', roles: ["bdd"], isShiny: false },
    { dex: 569, name: 'Garbodor', roles: ["otdd"], isShiny: false },
    { dex: 94, name: 'Gengar', roles: ["bdd"], isShiny: false },
    { dex: 596, name: 'Giant Galvantula', roles: ["bdd"], isShiny: false },
    { dex: 362, name: 'Glalie', roles: ["bdd"], isShiny: false },
    { dex: 673, name: 'Gogoat', roles: ["otdd"], isShiny: false },
    { dex: 76, name: 'Golem', roles: ["bdd"], isShiny: false },
    { dex: 706, name: 'Goodra', roles: ["tank"], isShiny: false },
    { dex: 576, name: 'Gothitelle', roles: ["otdd"], isShiny: false },
    { dex: 210, name: 'Granbull', roles: ["bdd"], isShiny: false },
    { dex: 130, name: 'Gyarados', roles: ["bdd"], isShiny: false },
    { dex: 858, name: 'Hatterene', roles: ["bdd"], isShiny: false },
    { dex: 612, name: 'Haxorus', roles: ["otdd"], isShiny: false },
    { dex: 485, name: 'Heatran', roles: ["otdd"], isShiny: false },
    { dex: 450, name: 'Hippowdon Female', roles: ["bdd"], isShiny: false },
    { dex: 211, name: 'Hisuian Qwilfish', roles: ["bdd"], isShiny: false },
    { dex: 157, name: 'Hisuian Typhlosion', roles: ["bdd"], isShiny: false },
    { dex: 635, name: 'Hydreigon', roles: ["otdd"], isShiny: false },
    { dex: 135, name: 'Jolteon', roles: ["bdd"], isShiny: false },
    { dex: 402, name: 'Kricketune', roles: ["bdd"], isShiny: false },
    { dex: 470, name: 'Leafeon', roles: ["tank"], isShiny: false },
    { dex: 25, name: 'Light Ball Pikachu', roles: ["otdd"], isShiny: false },
    { dex: 549, name: 'Lilligant', roles: ["bdd"], isShiny: false },
    { dex: 745, name: 'Lycanroc', roles: ["bdd"], isShiny: false },
    { dex: 745, name: 'Lycanroc Dusk Form', roles: ["otdd"], isShiny: false },
    { dex: 68, name: 'Machamp', roles: ["bdd"], isShiny: false },
    { dex: 126, name: 'Magmar', roles: ["otdd"], isShiny: false },
    { dex: 82, name: 'Magneton', roles: ["bdd"], isShiny: false },
    { dex: 310, name: 'Manectric', roles: ["bdd"], isShiny: false },
    { dex: 460, name: 'Mega Abomasnow', roles: ["bdd"], isShiny: false },
    { dex: 142, name: 'Mega Aerodactyl', roles: ["otdd"], isShiny: false },
    { dex: 306, name: 'Mega Aggron', roles: ["bdd", "otdd"], isShiny: false },
    { dex: 334, name: 'Mega Altaria', roles: ["bdd"], isShiny: false },
    { dex: 531, name: 'Mega Audino', roles: ["bdd"], isShiny: false },
    { dex: 0, name: 'Mega Banette', roles: ["bdd"], isShiny: false },
    { dex: 689, name: 'Mega Barbaracle', roles: ["bdd"], isShiny: false },
    { dex: 15, name: 'Mega Beedrill', roles: ["bdd"], isShiny: false },
    { dex: 0, name: 'Mega Blastoise', roles: ["bdd"], isShiny: false },
    { dex: 257, name: 'Mega Blaziken', roles: ["otdd"], isShiny: false },
    { dex: 0, name: 'Mega Chandelure', roles: ["bdd"], isShiny: false },
    { dex: 6, name: 'Mega Charizard X', roles: ["bdd"], isShiny: false },
    { dex: 6, name: 'Mega Charizard Y', roles: ["bdd"], isShiny: false },
    { dex: 36, name: 'Mega Clefable', roles: ["bdd"], isShiny: false },
    { dex: 149, name: 'Mega Dragonite', roles: ["bdd"], isShiny: false },
    { dex: 780, name: 'Mega Drampa', roles: ["bdd"], isShiny: false },
    { dex: 604, name: 'Mega Eelektross', roles: ["bdd"], isShiny: false },
    { dex: 160, name: 'Mega Feraligatr', roles: ["bdd"], isShiny: false },
    { dex: 478, name: 'Mega Froslass', roles: ["bdd"], isShiny: false },
    { dex: 445, name: 'Mega Garchomp', roles: ["bdd"], isShiny: false },
    { dex: 0, name: 'Mega Glalie', roles: ["bdd"], isShiny: false },
    { dex: 130, name: 'Mega Gyarados', roles: ["bdd"], isShiny: false },
    { dex: 701, name: 'Mega Hawlucha', roles: ["bdd"], isShiny: false },
    { dex: 214, name: 'Mega Heracross', roles: ["bdd"], isShiny: false },
    { dex: 0, name: 'Mega Houndoom', roles: ["otdd"], isShiny: false },
    { dex: 428, name: 'Mega Lopunny', roles: ["otdd"], isShiny: false },
    { dex: 448, name: 'Mega Lucario', roles: ["bdd"], isShiny: false },
    { dex: 310, name: 'Mega Manectric', roles: ["bdd"], isShiny: false },
    { dex: 154, name: 'Mega Meganium', roles: ["bdd"], isShiny: false },
    { dex: 0, name: 'Mega Metagross', roles: ["otdd"], isShiny: false },
    { dex: 18, name: 'Mega Pidgeot', roles: ["bdd"], isShiny: false },
    { dex: 0, name: 'Mega Pinsir', roles: ["bdd"], isShiny: false },
    { dex: 302, name: 'Mega Sableye', roles: ["bdd"], isShiny: false },
    { dex: 254, name: 'Mega Sceptile', roles: ["bdd"], isShiny: false },
    { dex: 212, name: 'Mega Scizor', roles: ["bdd", "otdd"], isShiny: false },
    { dex: 545, name: 'Mega Scolipede', roles: ["bdd"], isShiny: false },
    { dex: 227, name: 'Mega Skarmory', roles: ["bdd"], isShiny: false },
    { dex: 121, name: 'Mega Starmie', roles: ["bdd"], isShiny: false },
    { dex: 208, name: 'Mega Steelix', roles: ["bdd"], isShiny: false },
    { dex: 260, name: 'Mega Swampert', roles: ["bdd"], isShiny: false },
    { dex: 248, name: 'Mega Tyranitar', roles: ["otdd"], isShiny: false },
    { dex: 3, name: 'Mega Venusaur', roles: ["bdd"], isShiny: false },
    { dex: 71, name: 'Mega Victreebel', roles: ["bdd"], isShiny: false },
    { dex: 678, name: 'Meowstic', roles: ["bdd"], isShiny: false },
    { dex: 375, name: 'Metang', roles: ["bdd"], isShiny: false },
    { dex: 620, name: 'Mienshao', roles: ["otdd"], isShiny: false },
    { dex: 262, name: 'Mightyena', roles: ["otdd"], isShiny: false },
    { dex: 429, name: 'Mismagius', roles: ["otdd"], isShiny: false },
    { dex: 122, name: 'Mr.Mime', roles: ["bdd"], isShiny: false },
    { dex: 750, name: 'Mudsdale', roles: ["tank"], isShiny: false },
    { dex: 89, name: 'Muk', roles: ["bdd"], isShiny: false },
    { dex: 34, name: 'Nidoking', roles: ["bdd"], isShiny: false },
    { dex: 31, name: 'Nidoqueen', roles: ["bdd"], isShiny: false },
    { dex: 38, name: 'Ninetales', roles: ["bdd"], isShiny: false },
    { dex: 715, name: 'Noivern', roles: ["otdd"], isShiny: false },
    { dex: 139, name: 'Omastar', roles: ["otdd"], isShiny: false },
    { dex: 770, name: 'Palossand', roles: ["sot"], isShiny: false },
    { dex: 863, name: 'Perrserker', roles: ["bdd"], isShiny: false },
    { dex: 18, name: 'Pidgeot', roles: ["bdd"], isShiny: false },
    { dex: 474, name: 'Porygon-Z', roles: ["otdd"], isShiny: false },
    { dex: 668, name: 'Pyroar Female', roles: ["tank"], isShiny: true },
    { dex: 26, name: 'Raichu', roles: ["bdd"], isShiny: false },
    { dex: 409, name: 'Rampardos', roles: ["bdd"], isShiny: false },
    { dex: 407, name: 'Roserade', roles: ["bdd"], isShiny: false },
    { dex: 479, name: 'Rotom', roles: ["otdd"], isShiny: false },
    { dex: 373, name: 'Salamence', roles: ["bdd"], isShiny: false },
    { dex: 539, name: 'Sawk', roles: ["bdd"], isShiny: false },
    { dex: 254, name: 'Sceptile', roles: ["otdd"], isShiny: false },
    { dex: 336, name: 'Seviper', roles: ["bdd"], isShiny: false },
    { dex: 306, name: 'Shiny  Aggron', roles: ["otdd"], isShiny: true },
    { dex: 681, name: 'Shiny Aegislash', roles: ["bdd"], isShiny: true },
    { dex: 65, name: 'Shiny Alakazam', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 181, name: 'Shiny Ampharos', roles: ["otdd"], isShiny: true },
    { dex: 24, name: 'Shiny Arbok', roles: ["otdd"], isShiny: true },
    { dex: 59, name: 'Shiny Arcanine', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 267, name: 'Shiny Beautifly', roles: ["otdd"], isShiny: true },
    { dex: 15, name: 'Shiny Beedrill', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Blastoise', roles: ["otdd"], isShiny: true },
    { dex: 437, name: 'Shiny Bronzong', roles: ["bdd"], isShiny: true },
    { dex: 12, name: 'Shiny Butterfree', roles: ["bdd"], isShiny: true },
    { dex: 609, name: 'Shiny Chandelure', roles: ["bdd"], isShiny: true },
    { dex: 6, name: 'Shiny Charizard', roles: ["otdd"], isShiny: true },
    { dex: 815, name: 'Shiny Cinderace', roles: ["bdd"], isShiny: true },
    { dex: 879, name: 'Shiny Copperajah', roles: ["bdd"], isShiny: true },
    { dex: 225, name: 'Shiny Delibird', roles: ["bdd"], isShiny: true },
    { dex: 655, name: 'Shiny Delphox', roles: ["otdd"], isShiny: true },
    { dex: 87, name: 'Shiny Dewgong', roles: ["bdd"], isShiny: true },
    { dex: 232, name: 'Shiny Donphan', roles: ["bdd"], isShiny: true },
    { dex: 148, name: 'Shiny Dragonair', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 621, name: 'Shiny Druddigon', roles: ["bdd"], isShiny: true },
    { dex: 604, name: 'Shiny Eelektross', roles: ["otdd"], isShiny: true },
    { dex: 125, name: 'Shiny Electabuzz', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 101, name: 'Shiny Electrode', roles: ["bdd"], isShiny: true },
    { dex: 239, name: 'Shiny Elekid', roles: ["bdd"], isShiny: true },
    { dex: 395, name: 'Shiny Empoleon', roles: ["otdd"], isShiny: true },
    { dex: 196, name: 'Shiny Espeon', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Fearow', roles: ["otdd"], isShiny: true },
    { dex: 160, name: 'Shiny Feraligatr', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Flareon', roles: ["otdd"], isShiny: true },
    { dex: 419, name: 'Shiny Floatzel', roles: ["bdd"], isShiny: true },
    { dex: 205, name: 'Shiny Forretress', roles: ["otdd"], isShiny: true },
    { dex: 478, name: 'Shiny Froslass', roles: ["bdd"], isShiny: true },
    { dex: 475, name: 'Shiny Gallade', roles: ["otdd"], isShiny: true },
    { dex: 569, name: 'Shiny Garbodor', roles: ["bdd"], isShiny: true },
    { dex: 282, name: 'Shiny Gardevoir', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Gengar', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 129, name: 'Shiny Giant Magikarp', roles: ["otdd"], isShiny: true },
    { dex: 471, name: 'Shiny Glaceon', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 673, name: 'Shiny Gogoat', roles: ["otdd"], isShiny: true },
    { dex: 55, name: 'Shiny Golduck', roles: ["otdd"], isShiny: true },
    { dex: 575, name: 'Shiny Gothitelle', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Granbull', roles: ["otdd"], isShiny: true },
    { dex: 326, name: 'Shiny Grumpig', roles: ["tank"], isShiny: true },
    { dex: 130, name: 'Shiny Gyarados', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 93, name: 'Shiny Haunter', roles: ["bdd"], isShiny: true },
    { dex: 631, name: 'Shiny Heatmor', roles: ["bdd"], isShiny: true },
    { dex: 214, name: 'Shiny Heracross', roles: ["otdd"], isShiny: true },
    { dex: 430, name: 'Shiny Honchkrow', roles: ["otdd"], isShiny: true },
    { dex: 229, name: 'Shiny Houndoom', roles: ["otdd"], isShiny: true },
    { dex: 635, name: 'Shiny Hydreigon', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Infernape', roles: ["otdd"], isShiny: true },
    { dex: 0, name: 'Shiny Jolteon', roles: ["otdd"], isShiny: true },
    { dex: 189, name: 'Shiny Jumpluff', roles: ["bdd"], isShiny: true },
    { dex: 124, name: 'Shiny Jynx', roles: ["bdd"], isShiny: true },
    { dex: 64, name: 'Shiny Kadabra', roles: ["bdd"], isShiny: true },
    { dex: 99, name: 'Shiny Kingler', roles: ["bdd"], isShiny: true },
    { dex: 601, name: 'Shiny Klinklang', roles: ["tank"], isShiny: true },
    { dex: 402, name: 'Shiny Kricketune', roles: ["bdd"], isShiny: true },
    { dex: 553, name: 'Shiny Krookodile', roles: ["bdd"], isShiny: true },
    { dex: 305, name: 'Shiny Lairon', roles: ["bdd"], isShiny: true },
    { dex: 171, name: 'Shiny Lanturn', roles: ["otdd"], isShiny: true },
    { dex: 470, name: 'Shiny Leafeon', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 549, name: 'Shiny Lilligant', roles: ["sot"], isShiny: true },
    { dex: 405, name: 'Shiny Luxray', roles: ["bdd"], isShiny: true },
    { dex: 68, name: 'Shiny Machamp', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Magby', roles: ["bdd"], isShiny: true },
    { dex: 219, name: 'Shiny Magcargo', roles: ["otdd"], isShiny: true },
    { dex: 126, name: 'Shiny Magmar', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 82, name: 'Shiny Magneton', roles: ["otdd"], isShiny: true },
    { dex: 462, name: 'Shiny Magnezone', roles: ["otdd"], isShiny: true },
    { dex: 310, name: 'Shiny Manectric', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 226, name: 'Shiny Mantine', roles: ["bdd"], isShiny: true },
    { dex: 105, name: 'Shiny Marowak', roles: ["otdd"], isShiny: true },
    { dex: 0, name: 'Shiny Mawile', roles: ["bdd"], isShiny: true },
    { dex: 620, name: 'Shiny Mienshao', roles: ["bdd"], isShiny: true },
    { dex: 122, name: 'Shiny Mr.Mime', roles: ["otdd"], isShiny: true },
    { dex: 89, name: 'Shiny Muk', roles: ["otdd"], isShiny: true },
    { dex: 38, name: 'Shiny Ninetales', roles: ["bdd"], isShiny: true },
    { dex: 164, name: 'Shiny Noctowl', roles: ["tank"], isShiny: true },
    { dex: 224, name: 'Shiny Octillery', roles: ["otdd"], isShiny: true },
    { dex: 417, name: 'Shiny Pachirisu', roles: ["bdd"], isShiny: true },
    { dex: 47, name: 'Shiny Parasect', roles: ["bdd"], isShiny: true },
    { dex: 18, name: 'Shiny Pidgeot', roles: ["bdd"], isShiny: true },
    { dex: 25, name: 'Shiny Pikachu', roles: ["bdd"], isShiny: true },
    { dex: 127, name: 'Shiny Pinsir', roles: ["otdd"], isShiny: true },
    { dex: 57, name: 'Shiny Primeape', roles: ["bdd"], isShiny: true },
    { dex: 247, name: 'Shiny Pupitar', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 195, name: 'Shiny Quagsire', roles: ["bdd"], isShiny: true },
    { dex: 211, name: 'Shiny Qwilfish', roles: ["otdd"], isShiny: true },
    { dex: 26, name: 'Shiny Raichu', roles: ["bdd"], isShiny: true },
    { dex: 409, name: 'Shiny Rampardos', roles: ["bdd"], isShiny: true },
    { dex: 479, name: 'Shiny Rotom (mow)', roles: ["otdd"], isShiny: true },
    { dex: 28, name: 'Shiny Sandslash', roles: ["otdd"], isShiny: true },
    { dex: 254, name: 'Shiny Sceptile', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Scizor', roles: ["bdd"], isShiny: true },
    { dex: 123, name: 'Shiny Scyther', roles: ["otdd"], isShiny: true },
    { dex: 213, name: 'Shiny Shuckle', roles: ["tank"], isShiny: true },
    { dex: 227, name: 'Shiny Skarmory', roles: ["otdd"], isShiny: true },
    { dex: 80, name: 'Shiny Slowbro', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Snorlax', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 317, name: 'Shiny Swalot', roles: ["sot"], isShiny: true },
    { dex: 700, name: 'Shiny Sylveon', roles: ["bdd", "otdd"], isShiny: true },
    { dex: 114, name: 'Shiny Tangela', roles: ["otdd"], isShiny: true },
    { dex: 73, name: 'Shiny Tentacruel', roles: ["otdd"], isShiny: true },
    { dex: 777, name: 'Shiny Togedemaru', roles: ["sot"], isShiny: true },
    { dex: 468, name: 'Shiny Togekiss', roles: ["otdd"], isShiny: true },
    { dex: 389, name: 'Shiny Torterra', roles: ["otdd"], isShiny: true },
    { dex: 849, name: 'Shiny Toxtricity', roles: ["bdd"], isShiny: true },
    { dex: 157, name: 'Shiny Typhlosion', roles: ["bdd"], isShiny: true },
    { dex: 0, name: 'Shiny Vaporeon', roles: ["otdd"], isShiny: true },
    { dex: 0, name: 'Shiny Venusaur', roles: ["bdd"], isShiny: true },
    { dex: 71, name: 'Shiny Victreebel', roles: ["bdd"], isShiny: true },
    { dex: 738, name: 'Shiny Vikavolt', roles: ["otdd"], isShiny: true },
    { dex: 0, name: 'Shiny Vileplume', roles: ["otdd"], isShiny: true },
    { dex: 461, name: 'Shiny Weavile', roles: ["otdd"], isShiny: true },
    { dex: 110, name: 'Shiny Weezing', roles: ["tank"], isShiny: true },
    { dex: 40, name: 'Shiny Wigglytuff', roles: ["otdd"], isShiny: true },
    { dex: 178, name: 'Shiny Xatu', roles: ["otdd"], isShiny: true },
    { dex: 469, name: 'Shiny Yanmega', roles: ["bdd"], isShiny: true },
    { dex: 523, name: 'Shiny Zebstrika', roles: ["otdd"], isShiny: true },
    { dex: 865, name: 'Sirfetch\'d', roles: ["bdd"], isShiny: false },
    { dex: 903, name: 'Sneasler', roles: ["otdd"], isShiny: false },
    { dex: 338, name: 'Solrock', roles: ["bdd"], isShiny: false },
    { dex: 442, name: 'Spiritomb', roles: ["sot"], isShiny: false },
    { dex: 398, name: 'Staraptor', roles: ["bdd"], isShiny: false },
    { dex: 700, name: 'Sylveon', roles: ["otdd"], isShiny: false },
    { dex: 73, name: 'Tentacruel', roles: ["otdd"], isShiny: false },
    { dex: 538, name: 'Throh', roles: ["tank"], isShiny: false },
    { dex: 468, name: 'Togekiss', roles: ["otdd"], isShiny: false },
    { dex: 176, name: 'Togetic', roles: ["bdd"], isShiny: false },
    { dex: 357, name: 'Tropius', roles: ["bdd"], isShiny: false },
    { dex: 157, name: 'Typhlosion', roles: ["bdd"], isShiny: false },
    { dex: 201, name: 'Unown Legion', roles: ["sot"], isShiny: false },
    { dex: 901, name: 'Ursaluna', roles: ["otdd"], isShiny: false },
    { dex: 584, name: 'Vanilluxe', roles: ["bdd"], isShiny: false },
    { dex: 134, name: 'Vaporeon', roles: ["bdd"], isShiny: false },
    { dex: 416, name: 'Vespiquen', roles: ["otdd"], isShiny: false },
    { dex: 202, name: 'Wobbuffet', roles: ["otdd"], isShiny: false },
    { dex: 413, name: 'Wormadam', roles: ["bdd"], isShiny: false },
    { dex: 899, name: 'Wyrdeer', roles: ["bdd"], isShiny: false },
    { dex: 469, name: 'Yanmega', roles: ["otdd"], isShiny: false },
    { dex: 571, name: 'Zoroark', roles: ["bdd"], isShiny: false }
];

const dummyTeams = [
    {
        id: 1,
        content: "Nightmare Terrors",
        difficulty: "Nightmare",
        leader: "Xandy",
        clan: "volcanic",
        clanName: "Volcanic",
        level: 605,
        dex: 6,
        reqLvl: 400,
        players: 3,
        maxPlayers: 4,
        type: "quests",
        roles: [
            { type: "otdd", filled: true, title: "Shiny Charizard (OTDD)" },
            { type: "otdd", filled: true, title: "Shiny Blastoise (OTDD)" },
            { type: "bdd", filled: true, title: "Mega Alakazam (BDD)" },
            { type: "sot", filled: false, title: "Support" },
            { type: "tank", filled: false, title: "Tanker" }
        ],
        comment: "full travel"
    },
    {
        id: 2,
        content: "Koga Quest",
        difficulty: "Normal",
        leader: "Misty",
        clan: "seavell",
        clanName: "Seavell",
        level: 420,
        dex: 121,
        reqLvl: 300,
        players: 2,
        maxPlayers: 4,
        type: "quests",
        roles: [
            { type: "bdd", filled: true, title: "Mega Starmie (BDD)" },
            { type: "bdd", filled: true, title: "Shiny Wigglytuff (SOT)" },
            { type: "sot", filled: false, title: "Suporte" },
            { type: "tank", filled: false, title: "Tank" }
        ],
        comment: "Fazendo a quest pela primeira vez."
    },
    {
        id: 3,
        content: "Legendary Beasts",
        difficulty: "Hard",
        leader: "Brock",
        clan: "orebound",
        clanName: "Orebound",
        level: 550,
        dex: 208,
        reqLvl: 450,
        players: 4,
        maxPlayers: 5,
        type: "quests",
        roles: [
            { type: "otanker", filled: true, title: "Mega Steelix (Offensive Tank)" },
            { type: "sot", filled: true, title: "Aromatisse (SOT)" },
            { type: "bdd", filled: true, title: "Shiny Machamp (BDD)" },
            { type: "otdd", filled: true, title: "Shiny Gengar (OTDD)" },
            { type: "bdd", filled: false, title: "Burst DPS" }
        ],
        comment: "Suicune run, precisa de muito dano."
    }
];
